# Generated by Django 5.0.2 on 2024-02-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="friends", to="app.friend"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="app/img/default_profile.png", upload_to="profile_pics"
            ),
        ),
    ]
